version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - patrickhulce
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
